# Generated by Django 5.0.6 on 2024-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_creacion',
            field=models.DateField(default=1, verbose_name='fecha_creacion'),
            preserve_default=False,
        ),
    ]
