# Generated by Django 5.0.6 on 2024-07-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fecha_creacion',
        ),
    ]
